/:
  controller: Base
  action: index

/contact:
  controller: Base
  action: contact

/mon-super-portfolio:
  controller: Base
  action: portfolio



/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register

/forgot-password:
  controller: Auth
  action: forgotPassword

/reset-password:
  controller: Auth
  action: resetPassword

/activate:
  controller: Auth
  action: activate



/admin/pages:
  controller: PageController
  action: index

/admin/pages/add:
  controller: PageController
  action: create

/admin/pages/edit:
  controller: PageController
  action: edit

/admin/pages/delete:
  controller: PageController
  action: delete



/admin/users:
  controller: UserController
  action: index

/admin/users/create:
  controller: UserController
  action: create

/admin/users/edit:
  controller: UserController
  action: edit

/admin/users/delete:
  controller: UserController
  action: delete
