/:
  controller: Base
  action: index

/contact:
  controller: Base
  action: contact


/mon-super-portfolio:
  controller: Base
  action: portfolio







/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register

/admin/pages:
  controller: PageController
  action: index

/admin/pages/add:
  controller: PageController
  action: create

/admin/pages/delete:
  controller: PageController
  action: delete

/admin/users:
  controller: UserController
  action: index

/admin/users/delete:
  controller: UserController
  action: delete